# Generated by Django 5.0.3 on 2024-04-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yerkir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Yerkri anuny')),
                ('img', models.ImageField(max_length=250, upload_to='', verbose_name='Yerkri nkary')),
            ],
            options={
                'verbose_name': 'Yerkir',
                'verbose_name_plural': 'Yerkrner',
            },
        ),
    ]
