# Generated by Django 5.0.3 on 2024-04-04 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yerkir',
            name='img',
            field=models.ImageField(upload_to='yerkir/', verbose_name='Yerkri nkary'),
        ),
        migrations.CreateModel(
            name='Qaxaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Qaxaqi anuny')),
                ('Yerkir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yer_qaxaq', to='main.yerkir')),
            ],
            options={
                'verbose_name': 'Qaxaq',
                'verbose_name_plural': 'Qaxaqner',
            },
        ),
    ]
