# Generated by Django 5.0.3 on 2024-04-04 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_poxoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shenq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Shenqi hamary')),
                ('Poxoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yer_shenq', to='main.poxoc')),
            ],
            options={
                'verbose_name': 'Shenq',
                'verbose_name_plural': 'Shenqer',
            },
        ),
    ]
