# Generated by Django 5.0.3 on 2024-04-04 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shenq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bnakaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Bnakarani hamary')),
                ('Shenq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yer_bnakaran', to='main.shenq')),
            ],
            options={
                'verbose_name': 'Bnakaran',
                'verbose_name_plural': 'Bnakaranner',
            },
        ),
    ]
