# Generated by Django 5.0.3 on 2024-04-08 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molorak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Molorak hamary')),
                ('Bnakaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yer_molorak', to='main.bnakaran')),
            ],
            options={
                'verbose_name': 'Molorak',
                'verbose_name_plural': 'Molorakner',
            },
        ),
    ]
